#define KC_QWER KC_FN0
#define KC_DVOR KC_FN1
#define KC_COLE KC_FN2
#define KC_GAME KC_FN3

#define KC_SPFN KC_FN4
#define KC_ENFN KC_FN5
#define KC_SETT KC_FN6
#define KC_TFN  KC_FN7
#define KC_TCTL KC_FN8

#define KC_CTLQ KC_FN9
#define KC_CTLC KC_FN10

#define KC_MSIG KC_FN11

enum keycode_fn_custom {
    QWER,
    DVOR,
    COLE,
    GAME,

    SPFN,
    ENFN,
    SETT,
    TFN,
    TCTL,

    CTLQ,
    CTLC,

    MSIG
};

const action_t PROGMEM fn_actions[] = {
    [QWER]   = ACTION_FUNCTION(F_SWITCH_LAYOUT_QWERTY),
    [DVOR]   = ACTION_FUNCTION(F_SWITCH_LAYOUT_DVORAK),
    [COLE]   = ACTION_FUNCTION(F_SWITCH_LAYOUT_COLEMAK),
    [GAME]   = ACTION_FUNCTION(F_SWITCH_LAYOUT_GAMER),

    [SPFN]   = ACTION_LAYER_TAP_KEY(L_OVERLAY_HHKB_FN, KC_SPC),
    [ENFN]   = ACTION_LAYER_TAP_KEY(L_OVERLAY_HHKB_FN, KC_ENTER),
    [SETT]   = ACTION_LAYER_TAP_KEY(L_OVERLAY_KEYMAP_SETTINGS, KC_APP),
    [TFN]    = ACTION_LAYER_TOGGLE(L_FN_SPACEFN),
    [TCTL]   = ACTION_LAYER_TOGGLE(L_OVERLAY_CTRL_REMAP),

    [CTLQ]   = ACTION_FUNCTION(F_CTRL_QWERTY_FALLBACK),
    [CTLC]   = ACTION_MODS_TAP_KEY(MOD_RCTL, KC_CAPS),

    [MSIG]   = ACTION_MACRO(M_SIGNATURE),
};
