#define F_SWITCH_LAYOUT_QWERTY      0
#define F_SWITCH_LAYOUT_DVORAK      1
#define F_SWITCH_LAYOUT_COLEMAK     2
#define F_SWITCH_LAYOUT_GAMER       3
#define F_CTRL_QWERTY_FALLBACK      4
#define F_KP_SWITCH_LAYOUT_NUMPAD   5
#define F_KP_SWITCH_LAYOUT_GAMER    6
