#define L_QWERTY                    0
#define L_DVORAK                    1
#define L_COLEMAK                   2
#define L_OVERLAY_CTRL_REMAP        3
#define L_OVERLAY_HHKB_FN           4
#define L_FN_SPACEFN                5
#define L_OVERLAY_GAMER             6
#define L_OVERLAY_KEYMAP_SETTINGS   7
#define L_FN_PRIMARY                8
