enum keymap_layer {
    L_QWERTY,
    L_DVORAK,
    L_COLEMAK,
    L_OVERLAY_CTRL_REMAP,
    L_OVERLAY_HHKB_FN,
    L_FN_SPACEFN,
    L_OVERLAY_GAMER,
    L_OVERLAY_KEYMAP_SETTINGS,
    L_FN_PRIMARY,
};
